### ISSUE TITLE
Compatibility issue with IE 11 and weird native issue

### ISSUE THREAD

**Issue by chrisghub** [TypeCtrl/ngx-emoji-mart#105]
After upgrading to the newest version which included the fix for the unsupported emojis, I raised in an earlier issue I now have the following problems:

- In IE 11 I get console errors because somewhere 'includes' is used (screenshot below)
- If I don't explicitly use native="false" on the ngx-emoji component I get duplicated emojis, but even when I set the native attribute and I inspect the DOM I still see the span with background image but it also has the unicode emoji as content inside the span (screenshot also below)

![emoji_dup_error](https://user-images.githubusercontent.com/9772738/40653377-3a151c98-633b-11e8-8105-35d839b8a2d1.png)
![emoji_error_ie](https://user-images.githubusercontent.com/9772738/40653378-3a2d5aba-633b-11e8-8a41-9f83acb1a64e.png)

**Comment by DanielKucal** [comment]
1. Do you have polyfills for IE uncommented?
2. Hmm, the emoji in content is to make it copyable (e.g. on other sites). It probably can be solved by additional styling for IE.

**Comment by chrisghub** [comment]
Thanks that did it!
