### ISSUE TITLE
Reverse sorting of emoji mart in IE 11

### ISSUE THREAD

**Issue by chrisghub** [TypeCtrl/ngx-emoji-mart#111]
The sorting of the emojis seems to be different in IE 11. In chrome and firefox smiles are displayed first whereas IE 11 displays all the flags first. This is very annoying for users because this means the most used emojis are somewhere on the bottom. The most recent section is the same on IE and other browsers

**Comment by chrisghub** [comment]
Any news or progress on this?

**Comment by scttcper** [comment]
I think i've fixed it with https://github.com/TypeCtrl/ngx-emoji-mart/commit/626ec4c09d2c70a32d4ec63970b133705fbf0d13
