### ISSUE TITLE
Filter Not Working

### ISSUE THREAD

**Issue by narendraraghuwanshi** [TypeCtrl/ngx-emoji-mart#118]
Filter not working when i initialise it after click on any emoji filter work perfect
![screenshot 1](https://user-images.githubusercontent.com/26792935/41709360-9d030590-7560-11e8-969b-0397a2d4370c.png)

**Comment by F3LENYR** [comment]
Same problem :/
I use the last version (0.6.4)

Problem demo : https://gyazo.com/1c93f44ddeb3ddef412c7b96a803f6c8

**Comment by scttcper** [comment]
so far i'm not able to reproduce. is there a browser or something specific?

**Comment by narendraraghuwanshi** [comment]
i Use chrome Browser
and angular 5

**Comment by IamLance** [comment]
I have this same problem too. Angular 6 here

**Comment by scttcper** [comment]
I've tried to address this in v0.6.5
