### ISSUE TITLE
Howto: display emoji

### ISSUE THREAD

**Issue by wilson0506** [TypeCtrl/ngx-emoji-mart#139]
how to display the selected emoji into div?

**Comment by ndkcha** [comment]
add (emojiClick)="addEmoji($event)" event to your html binding.

and then in your add emoji function. 
(HTMLInputElement).value += event.emoji.native

I think it's already listed in the [README.md](https://github.com/TypeCtrl/ngx-emoji-mart#picker) file

**Comment by wilson0506** [comment]
Sorry for bothering, if use emoji native like 😍, 
it will show up accordingly to the platform, like iphone showing apple version.

How to apply theme to it, let say if i want to change to twitter version, what should i do?

one more question, is it possible to convert html into 
<ngx-emoji=':smiley" size="16"></ngx-emoji> by regex 
and display it using [innerHtml] or sth like that .

Cheers

**Comment by lentschi** [comment]
@wilson0506
```typescript

**Comment by NaimishVerma17** [comment]
innerHTML doesn't render html components....

**Comment by scttcper** [comment]
should be easier with the new function added to emoji service https://github.com/TypeCtrl/ngx-emoji-mart#display-emoji-as-custom-element

closing in favor of #89
