### ISSUE TITLE
Change cdn direction

### ISSUE THREAD

**Issue by jcangelosi** [TypeCtrl/ngx-emoji-mart#148]
Hello, I have been using this library and I'm wondering if there is any form to change the CDN given that I want to use it without direct access to internet and only using the native emojis brings a problem with the different OS (some users are using linux and w7 so they dont get most emojis)

**Comment by scttcper** [comment]
#133 shows how they're using it.

Its also in docs as `backgroundImageFn`

**Comment by jcangelosi** [comment]
Perfect, thanks !
