### ISSUE TITLE
How to change frequently used emojis count formula? 

### ISSUE THREAD

**Issue by eugeniumegherea** [TypeCtrl/ngx-emoji-mart#155]
Hello
In our design, we fit 13 emojis in one line, so, based on formula, that's 13 * 4 emojis displayed in 'frequently used' area. Because, the emoji picker container's height is small, frequently used uses way too much space.
I was wondering if there's a simple way to hardcode/change the calculation function so that we can get fewer frequently used emojis.
Thanks

**Comment by scttcper** [comment]
Added a totalFrequentLines parameter which should address this.
so it'll be 13 * totalFrequentLines
