### ISSUE TITLE
how to get custom emoji object.native icon if i am using image for custom emoji

### ISSUE THREAD

**Issue by shashiakosha** [TypeCtrl/ngx-emoji-mart#157]
suppose for this object 

let obj = {
  id: 'santa',
  name: 'Father Christmas',
  colons: ':santa::skin-tone-3:',
  text: '',
  emoticons: [],
  skin: 3,
  native: '🎅🏼'
}

HERE i am getting native icon by using obj.native to render in view

BUT HERE - in this case 

let obj1 =  {
  id: 'octocat',
  name: 'Octocat',
  colons: ':octocat',
  text: '',
  emoticons: [],
  custom: true,
  imageUrl: 'https://assets-cdn.github.com/images/icons/emoji/octocat.png?v7',
  native:'', 
}

How to get  obj1.native , and how to fill that native icon for custom emoji added.

**Comment by scttcper** [comment]
there isn't a native version of your custom icon because it isn't a native emoji. To display it you would need to use an img or a css background image

**Comment by shashiakosha** [comment]
@scttcper thanks for quick reply.
