### ISSUE TITLE
emojiSpriteStyles sample doesn't support skin variations

### ISSUE THREAD

**Issue by lentschi** [TypeCtrl/ngx-emoji-mart#165]
The sample you added under the headline `Display emoji as custom element` doesn't seem to support skin variations: `$event.emoji.sheet` doesn't contain any reference to the selected skin tone, so even if `emojiSpriteStyles` supported it (haven't checked!), it wouldn't get the information.

So the example code in your `README.md` always gives me sprites with pink faces.

**Comment by scttcper** [comment]
Oh thats a bug.
changed in v0.8.2. The sheet returned on click should now be the skinned sheet.
