### ISSUE TITLE
Double tap required on mobile devices

### ISSUE THREAD

**Issue by floAtEbcont** [TypeCtrl/ngx-emoji-mart#166]
When selecting an emoji from the picker on a touch screen device (I tried it on iPhone SE & iPad), two taps are required to trigger the `emojiSelect` and/or `emojiClick` events and close the picker.
That behavior might well be intended! (Otherwise, if `[showPreview]="true"` is set it would be impossible to see said preview.)

However - when setting `[showPreview]="true"` it would be useful to have it react to a single tap. Therefore I suggest adding a new boolean Input (e.g. `emitOnTouch`) that causes this behavior.

**Comment by edenchen123** [comment]
@scttcper tap still not working 

> "@ctrl/ngx-emoji-mart": "^0.14.0",
> Iphone X
