### ISSUE TITLE
modules not found

### ISSUE THREAD

**Issue by Lakston** [TypeCtrl/ngx-emoji-mart#168]
What I tried: 
`npm install @ctrl/ngx-emoji-mart`

imported both
```
import { PickerModule } from '@ctrl/ngx-emoji-mart'
import { EmojiModule } from '@ctrl/ngx-emoji-mart/ngx-emoji'
```
and added them to the import section of my ngmodule
added the css import

But I'm getting these error when I'm trying to serve my app:
```
node_modules/@ctrl/ngx-emoji-mart/anchors.component.d.ts(2,31): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/category.component.d.ts(2,37): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/emoji-frequently.service.d.ts(1,27): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/emoji-search.service.d.ts(1,41): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/picker.component.d.ts(2,61): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/preview.component.d.ts(2,48): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/skins.component.d.ts(2,23): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
src/modules/recognition/recognition.module.ts(33,29): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
```

I did an `npm ls @ctrl/ngx-emoji-mart` just to be sure and also checked node_modules and it's listed there.

I also tried to install the `0.9.0` release just in case the v0.10 was broken, same thing.

What am I doing wrong here ?

**Comment by Lakston** [comment]
Ok my bad I found both issues stating the same problem, in case anyone stumbles upon this one : you need a typescript version > 2.6

I'm now facing a problem `"export 'defineInjectable' was not found in '@angular/core'`
I'm guessing the lib is not compatible with Angular < 6 anymore ?

**Comment by scttcper** [comment]
You got it

**Comment by readme42** [comment]
It would be very helpful if you could mention which lib version is supported by which angular  in the readme.

**Comment by johnfrades** [comment]
Yeah would be good if you could list down what version of angular supports which version here.
Currently running angular 5

**Comment by quenneth-bidchat** [comment]
I'm facing the same issue with Angular 4. Can you please mention which version is compatible with Angular 4

**Comment by scttcper** [comment]
No versions are compatible with 4 this was made after.
