### ISSUE TITLE
Emojis are split vertically in Firefox

### ISSUE THREAD

**Issue by cozzbie** [TypeCtrl/ngx-emoji-mart#169]
![screenshot 2018-10-22 14 50 02](https://user-images.githubusercontent.com/3672236/47296610-b933d900-d60a-11e8-9ae3-46eee0a034ea.png)

I can raise a PR but this feels fairly straightforward by simply changing the `display` properties in `emoji.component.ts` to `inline` as opposed to `inline-block`.

**Comment by scttcper** [comment]
what version of firefox? looks fine here

**Comment by bisquitthe** [comment]
Same behavior with FF 64.0.2 in demo, but only with native set.
