### ISSUE TITLE
NullInjectorError: No provider for e! when adding this lib in a custom component

### ISSUE THREAD

**Issue by erikramalho** [TypeCtrl/ngx-emoji-mart#171]
I have a Angular 6 (Lazy Load) Application and I created a component do reuse the emoji picker across my application, It works fine. But once I try to use it in --prod mode, it shows me the error: 

`ERROR Error: StaticInjectorError(u)[e -> e]: 
  StaticInjectorError(Platform: core)[e -> e]: 
    NullInjectorError: No provider for e!
    at e.get (core.js:1062)
    at core.js:1307
    at e (core.js:1251)
    at e.get (core.js:1147)
    at core.js:1307
    at e (core.js:1251)
    at e.get (core.js:1147)
    at So (core.js:8328)
    at e.get (core.js:9020)
    at So (core.js:8328)`

I've followed the logs and figured out that the errors are in ctrl-ngx-emoji-mart.js: EmojiFrequentlyService and EmojiService that are not being found. I've added both as providers in my component (not sure if it's the right thing to do).

EmojiFrequentlyService worked, but EmojiService did not. I can't compile after adding because it throws this error: 

`Module not found: Error: Can't resolve '@ctrl/ngx-emoji-mart/ngx-emoji/public_api'`

Any clues for what is happening?

**Comment by hansifer** [comment]
@erikramalho we're running into this as well. did you ever find a solution?
