### ISSUE TITLE
Search returning no results when [include] or [exclude] set on <emoji-mart>

### ISSUE THREAD

**Issue by s-moran** [TypeCtrl/ngx-emoji-mart#172]
For example, using the code below gives a blank search results area. Should be able to search within 'people' category. Works as expected when [include] is removed.
   
```
<emoji-mart set="apple" [title]="''" [emojiSize]="16" [emoji]="''" 
[totalFrequentLines]="1" [perLine]="8" (emojiClick)="emojiClick($event)" [include]="['people']">
</emoji-mart>
```

**Comment by zoualmamy** [comment]
Any fix on this yet?

**Comment by scttcper** [comment]
I probably won't be able to get to this, please open a PR

**Comment by s-moran** [comment]
I'll try to take a look at it ... might also be related to #182

**Comment by mlembke1** [comment]
@scttcper Thanks for the new release. However, is there a fix for those of us who aren't on Angular 8 yet...?
