### ISSUE TITLE
ngx-emoji-mart problems with IE

### ISSUE THREAD

**Issue by jpcunha20** [TypeCtrl/ngx-emoji-mart#177]
Hi, i'm having problems with the package in IE. Any suggestion?

**Comment by jpcunha20** [comment]
Doesn't work at all :(

**Comment by s-moran** [comment]
What version of IE? Can you generate a minimal reproducible example?

**Comment by scttcper** [comment]
i opened latest IE on my desktop and it does seem broken in the demo.

**Comment by scttcper** [comment]
It works with all the pollyfills. Including es7/array
