### ISSUE TITLE
EmojiModule not found and could not use EmojiService in my component. Angular 7.1.0 and TypeScript 3.1.6

### ISSUE THREAD

**Issue by waleedramzan** [TypeCtrl/ngx-emoji-mart#185]
I am using ngx-emoji-mart in my angular chat application. I am using Angular 7.1.0 and TypeScript 3.1.6.

EmojiModule could not be resolved in my Chat Module. I cannot import it. Angular gives EmojiModule not resolved. Other than this, I could not use EmojiService in my component. I am importing EmojiService in my component like this: 
`constructor(public emoji: EmojiService) {}`

Component HTML:
`<emoji-mart (emojiClick)="addEmoji($event)"
            class='emoji-mart'></emoji-mart>`
TS:
//addEmoji function
`addEmoji(event){
    const styles = this.emoji.emojiSpriteStyles($event.emoji.sheet, 'twitter'); // pass emoji sheet
}`

I cannot use this.emoji.emojiSpriteStyles()
I have searched a lot around ngx-emoji-mart github issues but nothing worked for me. Thanks

**Comment by anikets43** [comment]
@waleedramzan 
This woeks
`import { EmojiService } from '@ctrl/ngx-emoji-mart/ngx-emoji';`
