### ISSUE TITLE
Improve emoji-mart picker performance

### ISSUE THREAD

**Issue by s-moran** [TypeCtrl/ngx-emoji-mart#189]
The current <emoji-mart> picker component is quite heavy (from a UI perspective) when showing all categories on picker popup (especially painful in IE11). From my experience, this is due to having too many components in an *ngFor. 

One potential solution would be to provide an option to "tab" the categories. So instead of having all emojis in one big list, you render a new tab each time the user selects a category from the top menu. That would make it fast since when the picker first appears it only loads one (the default) category instead of all of them at once.

**Comment by mlapaglia** [comment]
Putting the emojis into a [virtual scrollbox](https://material.angular.io/cdk/scrolling/overview#virtual-scrolling) would improve performance as well.

**Comment by mlapaglia** [comment]
https://github.com/TypeCtrl/ngx-emoji-mart/pull/202

**Comment by cslecours** [comment]
Does 0.17 fix your issues?  (ref: #215)
