### ISSUE TITLE
custom emojis broken

### ISSUE THREAD

**Issue by Eraldo** [TypeCtrl/ngx-emoji-mart#190]
When I try to do this:
`<ngx-emoji [custom]="customEmojis"></ngx-emoji>`

I get the following error:
```
Uncaught Error: Template parse errors:
Can't bind to 'custom' since it isn't a known property of 'ngx-emoji'.
```

I can indeed confirm in the source code that the emoji component does not accept a custom data array:
https://github.com/TypeCtrl/ngx-emoji-mart/blob/master/src/lib/emoji/emoji.component.ts#L83

I guess the documentation is out of sync: https://github.com/TypeCtrl/ngx-emoji-mart/blame/master/README.md#L249

What is the current/recommended way of rendering custom emojis?

**Comment by scttcper** [comment]
yeah i think you pass that to `[emoji]` need to update doc

**Comment by Eraldo** [comment]
To `[emoji]`??
I thought I the emoji parameter takes an emoji `id`, `colon` emoji name or an `emoji object`.

Context: I use the emoji picker (mart) to pick an emoji (in this case a custom one) and send the id to server (to store it in my database).
Now on the other end of things, I want to be able to display that custom emoji. (What I get from the server is the id.)

Currently if I provide the custom emoji id to the ngx-emoji tag as the emoji parameter, no emoji gets displayed (which I can understand since it does not "know" what to do with the custom id.

The docs actually did make sense to me. With `<ngx-emoji emoji="mycustomid" [custom]="customEmojis"></ngx-emoji>` I thought the id would tell which one to use and the custom parameter would inform the component of what custom data to include in the data set.

Another solution idea that I find suitable was to make it possible to provide a way for the EmojiService to add custom emojis. In that case, both the mart and emoji component could find and use the custom emojis and I would only need to provide and setup my custom data once. How about that? I tried to "hack" into the service but failed since the uncompression of the data seems to take place beforehand and I did not find a method to mount my custom emojis.

Anyway I would appreciate guidance on how to make my use case of "picking and displaying a custom emoji" work.

Thanks for the quick reply btw. :)

**Comment by scttcper** [comment]
`emoji object` is what you're passing to `[emoji]` where the object is your custom emoji. currently the service doesn't support adding custom emojis.

**Comment by Eraldo** [comment]
I have a python backend where I save the emoji ids not the full objects (which also makes more sense to me). Given such a custom emoji id I would like to display the emoji. Why id the custom option gone? It did make a lot of sense to me, just like it works with the mart (picker).
