### ISSUE TITLE
native default - Small confusing issue 

### ISSUE THREAD

**Issue by AndreyMig** [TypeCtrl/ngx-emoji-mart#2]
https://github.com/TypeCtrl/ngx-emoji-mart/blob/961df4b97747a46ff6c25c159084a24f1e182f0f/src/lib/picker/picker.component.ts#L73

I had some trouble getting started with the repo due to the documentation about the value for the default "native" property. If I'm not mistaken, The default is true but the documentation says it's false.

Anyways, great repo! thanks.

**Comment by scttcper** [comment]
thanks for reporting
