### ISSUE TITLE
showing emojis in black and white, I need in original way that are shown in the picker?

### ISSUE THREAD

**Issue by Bhushanjire** [TypeCtrl/ngx-emoji-mart#237]

**Comment by Bhushanjire** [comment]
I want to add emoji on my chat application. When I add any emoji on input I'm getting black and white emoji. I'm integrating in Angular 8.

I have used **ngx-emoji-mart version : 0.17.0**

**Inside app.module.ts :**
import { PickerModule } from '@ctrl/ngx-emoji-mart'
import { EmojiModule } from '@ctrl/ngx-emoji-mart/ngx-emoji'

imports: [
    PickerModule,
    EmojiModule
  ]



**Inside HTML I Added Following code :** 

 <emoji-mart  color="#FFFF99" class="emoji-mart" set="apple" (emojiSelect)="addEmoji($event)"
                            *ngIf="showEmojiPicker" title="Pick your emoji…"></emoji-mart>


 <i class="fa fa-grin handCursor" aria-hidden="true"
                                        (click)="toggleEmojiPicker()"></i>
                                    <input type="input" formControlName="message" class="inputMsg"
                                        placeholder="Type a message" name="chat_message" [(ngModel)]="chat_message">

**Inside TYpescript I have written following code:** 

 showEmojiPicker = false;

 toggleEmojiPicker() {
    this.showEmojiPicker = !this.showEmojiPicker;
  }

  addEmoji(event){
    const { chat_message } = this;
    const text = `${event.emoji.native}`;
console.log(event)

    this.chat_message = text;
    this.showEmojiPicker = false;
  }

I hope it's help to understand my issue. Please have a look and let me know if I'm doing something stupid stuff.

Thanks in Advance.

**Comment by scttcper** [comment]
are you using internet explorer or something?

**Comment by Bhushanjire** [comment]
Hello,
I am using Google Crome [Version 73.0.3683.103 (Official Build) (64-bit) ]
And on firefox[68.0.1 (64-bit)] same issue happened with some emojis.
Please see the attach screenshots of google crome and firefox
![crome_emoji_issue](https://user-images.githubusercontent.com/20113800/62596477-1978da80-b900-11e9-8659-6ee7a5181bc8.png)
![firefox_emoji_issue](https://user-images.githubusercontent.com/20113800/62596479-1aaa0780-b900-11e9-86c6-8c12ecce91fe.png)

**Comment by dineshrawat11** [comment]
Did you get any solution? Because My platform is same and I am facing the exact issue...

**Comment by davidtoral** [comment]
need help with this please

**Comment by dineshrawat11** [comment]
@davidtoral This is actually using the system/machine machines that cause the emojis are not coming colored. download them from here: https://www.google.com/get/noto/

**Comment by davidtoral** [comment]
@dineshrawat11 

thanks
