### ISSUE TITLE
Inconsiderate emoji shortName

### ISSUE THREAD

**Issue by raphaelM-sudo** [TypeCtrl/ngx-emoji-mart#238]
I am implementing a contenteditable text area in Angular with Emoji Mart to pick and add an emoji.
In addition I want to change text from the user input into an emoji if it matches a shortName or emoticon from Emoji Mart ( e.g. ":)" becomes 🙂 ).
My code is working, but I noticed that I could not write out a few emoji names ( e.g. ":ok :" or ":o)" would immediately become :o which displays 😮 ).

I have made a [spreadsheet](https://docs.google.com/spreadsheets/d/1j-IN3bl-RB7C5DEFvGZ9jHNp5fIC_J1CJxoBDbuVIPg/edit?usp=sharing) with all conflicting emojis.

Now there are workarounds to this, like parsing the text after a trailing whitespace only. But if the emoji is the last character, the user would have to enter another whitespace.
I don't want to make my text area component overly complicated, which it already is, since I have to work with contenteditable.

So my request is to change the prefix and postfix for the shortNames (or the names displayed in the preview) to something unique like "::" and change the emoticon of the monkey ":o)" which happens to be the only conflict in between emoticons.
I know this is a port from React, but it would be an improvement compared to the original component.

**Comment by jwhenry3** [comment]
Why not change the code on space, tab, or enter? this way you avoid the issue altogether?
