### ISSUE TITLE
Emojis not rendering in picker

### ISSUE THREAD

**Issue by Adnan-Shahid** [TypeCtrl/ngx-emoji-mart#239]
Hello, I've been using the emoji-mart and I noticed that the picker no longer seems to show the emojis (to click), but it only occurs on the live version and not within my local. There is no difference with the code to call it and I'm using angular 7

![Screen Shot 2019-08-19 at 2 59 40 PM](https://user-images.githubusercontent.com/20377903/63292087-e422a400-c292-11e9-9e7c-89df1396d9fd.png)

It appears as above on live, but normally on local and it seems to render everything except the emojis themselves? Below is how I am referencing it on the HTML level

`<div *ngIf="emoji">
          <emoji-mart
            style="zoom: 70%; width: 24em;"
            title="Pick your emoji"
            isNative="true"
            emoji="point_up"
            set="emojione"
            [style]="{ position: 'absolute', bottom: '2.6em', right: '0px'}"
            (emojiClick)="addEmoji($event); emoji=false;"
          >
          </emoji-mart>
        </div>`

**Comment by shyamal890** [comment]
Yes, there seems to be some error in latest release

**Comment by shyamal890** [comment]
@scttcper please have a look latest version has this issue.

**Comment by scttcper** [comment]
what version of angular are you using

**Comment by shyamal890** [comment]
@scttcper Alright I was able to find the issue. It seems like `quill.snow.css` is overriding `emoji-mart`'s css. 

Specifically if `emoji-mart` is triggered from `quill-toolbar`. The following css from `quill-snow` override `emoji-mart-emoji` css.

CSS from `.ql-snow.ql-toolbar button, .ql-snow .ql-toolbar button` overrides `emoji-mart-emoji`.

Adding following specifically to `emoji-mart-emoji` solved the issue for me:
```
.emoji-mart-emoji{
            float:none;
            height: 36px;
            width: 36px;
            padding: 6px;
        }
```

**Comment by scttcper** [comment]
should no longer be an issue
