### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by danimartinezsaa** [TypeCtrl/ngx-emoji-mart#246]
![1](https://user-images.githubusercontent.com/32169739/64983535-ffe48e80-d8c0-11e9-94ee-e32c87d5098e.PNG)
When I compile the application I get this error. I'm using version 7.2 of angular, node 11 and TS 3.2.4.

**Comment by candorthor** [comment]
@scurvyGosling 

Hi,

could you please tell how did you solve this issue?

**Comment by scttcper** [comment]
downgrade. angular 8 is required on the latest version
