### ISSUE TITLE
Emoji png gets downloaded very time 

### ISSUE THREAD

**Issue by alberk8** [TypeCtrl/ngx-emoji-mart#247]
If I have the below, when clicking on the emoji the 64.png gets downloaded very time a new emoji is clicked.  Why is the png not cached after the first load ?

`<emoji-mart set="apple" size="64"></emoji-mart>`

**Comment by alexanderyarm** [comment]
Please fix this asap.
It provides very bad experience to the users especially when you care about application performance.
Image size is huge 2.5 mb and it is loading every time after emoji select. For users with mobile connection it's very critical.

**Comment by kochax** [comment]
+1

**Comment by scttcper** [comment]
set the backgroundImageFn and serve the image from a server that sets caching headers
