### ISSUE TITLE
Emoji viewer emojiClick not firing when rendered inside of ngFor

### ISSUE THREAD

**Issue by singara-velan** [TypeCtrl/ngx-emoji-mart#248]
Snippet:

<ng-template ngFor let-emoji [ngForOf]="getGroupedEmojis()">
      <ngx-emoji [emoji]="emoji.key" set="twitter" sheetSize="32" size="25"
                        (emojiClick)="cb($event)"></ngx-emoji>
</ng-template>

Any one else facing this issue. The callback is not firing

**Comment by scttcper** [comment]
They're drawn in a ngFor loop in the emoji-mart so I'd assume it's something else

**Comment by singara-velan** [comment]
> They're drawn in a ngFor loop in the emoji-mart so I'd assume it's something else

 both click and over is having similar callback. its weird (emojiOver) is triggering but (emojiClick) not.
