### ISSUE TITLE
ERROR while ng serve

### ISSUE THREAD

**Issue by assadzakir** [TypeCtrl/ngx-emoji-mart#26]
![image](https://user-images.githubusercontent.com/5568769/37593917-905a27fc-2b95-11e8-9228-7d799ef2f57a.png)
![image](https://user-images.githubusercontent.com/5568769/37593983-c351a63a-2b95-11e8-9464-63add8a71fd0.png)

**Comment by scttcper** [comment]
dupe #1 use typescript > 2.6.2

**Comment by assadzakir** [comment]
yes its working now thanks :+1:
