### ISSUE TITLE
ngx-emoji should not render the emoji inside a button

### ISSUE THREAD

**Issue by homj** [TypeCtrl/ngx-emoji-mart#287]
**I propose that the change from `span` to `button` in 57fa8d043 should be reverted:**

In the commit 57fa8d043, the HTML-tag to render the emoji in `ngx-emoji` was changed from `span` to `button` to improve a11y. However, it is not clear to me, why the `button` tag should have any benefits over the `span` tag, since the `aria-label` attribute can be added to any HTML-tag.  Additionally, the use of the `button` tag is semantically incorrect, since emojis are not always clickable and buttons are only meant for clickable actions.
If in some cases (e.g. in the picker), the `ngx-emoji` should be clickable, it can instead be wrapped by a `button` tag.

**Comment by scttcper** [comment]
That's a good point. Here's what the emoji-mart library is doing https://github.com/missive/emoji-mart/blob/master/src/components/emoji/nimble-emoji.js#L182-L192 span by default but a button when an onclick is provided. Unfortunately, angular has no idea if you want an onclick.. interested in what you think about what they have

**Comment by homj** [comment]
Thanks for the quick reply!

I looked at the implementation in emoji-mart and i don't think this is doable with Angular. But I also don't think it is the correct way to tackle this 'issue'. The library shouldn't really care whether the `onclick` property has been provided or not. This should be handled by the developer that uses the component.

As I suggested, the `ngx-emoji` component could always be wrapped by a `button` tag if required. Alternatively, you could provide a `ngx-emoji-button` Component in addition to `ngx-emoji`

**Comment by prateekupadhyay** [comment]
https://github.com/TypeCtrl/ngx-emoji-mart/issues/279#issue-540981033
