### ISSUE TITLE
Close the emojo popup when click outside

### ISSUE THREAD

**Issue by akashdeepsharma1991** [TypeCtrl/ngx-emoji-mart#290]
Hii,

Is there any way that we can close the emoji pop when click outside on the page in mobile app. We are manually toggling the view but if user click outside the emoji box then the box should get close automactically.  Can any one help

**Comment by giancarlopostcron** [comment]
Did you recive any information about this ? @akashdeepsharma1991

**Comment by rahulsethKiwitech** [comment]
Any update on this ?

**Comment by mehars-jalin** [comment]
Anyone got solution?
