### ISSUE TITLE
Disable search bar

### ISSUE THREAD

**Issue by gitalvininfo** [TypeCtrl/ngx-emoji-mart#305]
Looks like enableSearch is not working. I've added this line enableSearch="false" and the search bar is still displaying. I've managed to hide the search bar through css but I want to do it on the other way around which is provided by this library "enableSearch". 
Is there I'm missing please bare with me. 
Thanks.

**Comment by scttcper** [comment]
make sure its false the boolean instead of the string `[enableSearch]="false"` and that you're on v2

**Comment by gitalvininfo** [comment]
Tried [enableSearch]="false" and the search bar is still displaying. What about v2 ? is that a version or what? 
Thanks

**Comment by scttcper** [comment]
https://github.com/TypeCtrl/ngx-emoji-mart/releases/tag/v2.0.0
