### ISSUE TITLE
Angular 9 Ivy problem

### ISSUE THREAD

**Issue by hrueger** [TypeCtrl/ngx-emoji-mart#306]
When I upgraded my project to Angular 9 and enabled the Ivy compiler, I started getting the following error:
![grafik](https://user-images.githubusercontent.com/18656830/75374025-96a17800-586f-11ea-8ec3-fa94e817fa26.png)

Unfortunately, I can't reproduce it with your sample application. My project is [AGM-Tools](github.com/hrueger/AGM-Tools) with the `ivy` branch. Any idea?

**Comment by scttcper** [comment]
seems to be working and building for me in a regular ivy angular 9 project
