### ISSUE TITLE
Demo on IE

### ISSUE THREAD

**Issue by Fzwael** [TypeCtrl/ngx-emoji-mart#310]
Hello,

I'm not sure if you guys are giving official support for IE or not but in my case I still have to work with it 😞 So I tried your [demo](https://ngx-emoji-mart.netlify.com/) on IE it works fine with native emojis.
But for other options it doesn't work and I get this error : 
ERROR TypeError: Object doesn't support property or method 'includes'

I assume it's an easy fix via the polyfills, so if you confirm that you are supporting IE, I can create a PR to fix this.

PS there was a similar issue to this here : #177

**Comment by scttcper** [comment]
You should be able to get pretty far using polyfills for IE
