### ISSUE TITLE
how to get unicode from emoji

### ISSUE THREAD

**Issue by sante85** [TypeCtrl/ngx-emoji-mart#327]
how to get unicode from emoji?

Best Regards

**Comment by sante85** [comment]
for example I pick 🐻 and return \ud83d\udc3b

**Comment by scttcper** [comment]
You'll need to use a converter of some kind https://stackoverflow.com/questions/48419167/how-to-convert-one-emoji-character-to-unicode-codepoint-number-in-javascript
