### ISSUE TITLE
It's possible to load the sprint locally?

### ISSUE THREAD

**Issue by dudipsh** [TypeCtrl/ngx-emoji-mart#329]
instead of doing this call
https://unpkg.com/emoji-datasource-apple@4.0.4/img/apple/sheets-256/64.png

**Comment by scttcper** [comment]
use `backgroundImageFn`

**Comment by dudipsh** [comment]
@scttcper thanks! 

https://github.com/TypeCtrl/ngx-emoji-mart/issues/133
