### ISSUE TITLE
OS Yosemite unsupported emoji

### ISSUE THREAD

**Issue by StoikovOleh** [TypeCtrl/ngx-emoji-mart#334]
hey, is there a way to not show unsupported emoji? 
For example, if you choose the orange heart on os Yosemite it will show just square

**Comment by StoikovOleh** [comment]
in theory, you can detect os version, and for emojis add smth like your:
`hidden: [
      'google',
      'twitter',
      'facebook'
 ]`
but for os

**Comment by scttcper** [comment]
this is why people like twitter and slack use images instead of unicode

**Comment by StoikovOleh** [comment]
yeah I got it, but the problem is that  I using it for input component of the email subject line and it doesn't support images.

So, my solution is:

use `<emoji-mart [emojisToShowFilter]="filter" [showSingleCategory]="false" >`

[showSingleCategory]="false" is mandatory if you don't want picker to stack when you select a category.

- filter emoji which rendering like a square:
```
filter(fullCode: string) {
    const code = fullCode.split('-')[0]
    
    if (!isNaN(Number(`0x${code}`))) {
      var canvas = document.createElement("canvas");
      var ctx = canvas.getContext("2d");;
      ctx.fillText(String.fromCodePoint(Number(`0x${code}`)), -2, 4);

      return ctx.getImageData(0, 0, 1, 1).data[3] > 0;
    } else {
      return false;
    }
  }

```
- or if you don't want to render even black emojis like on the screenshot below
![image](https://user-images.githubusercontent.com/17726380/81999694-8d4dcd80-965e-11ea-987b-513f291a14ac.png)

 you can use "if-emoji" lib:
```
filter(fullCode: string) {
    const code = fullCode.split('-')[0]
    
    if (!isNaN(Number(`0x${code}`))) {
      const emoji = String.fromCodePoint(Number(`0x${code}`));

      return ifEmoji(emoji);
    } else {
      return false;
    }
  }

```

**Comment by StoikovOleh** [comment]
better combine it: 

```
filter(fullCode: string) {
    const code = fullCode.split('-')[0]
    
    if (!isNaN(Number(`0x${code}`))) {
      var canvas = document.createElement("canvas");
      var ctx = canvas.getContext("2d");;
      ctx.fillText(String.fromCodePoint(Number(`0x${code}`)), -2, 4);

      return ctx.getImageData(0, 0, 1, 1).data[3] > 0 || ifEmoji(emoji);
    } else {
      return false;
    }
  }
```
