### ISSUE TITLE
when i use this one [emojisToShowFilter]="filter"  then emoji ui box taking more time to open

### ISSUE THREAD

**Issue by chirantan369** [TypeCtrl/ngx-emoji-mart#335]
Hi Team

Two issue i am getting.
1. [emojisToShowFilter]="filter" this one i am using for show emoji when are supported to browser. but when i use this after click on button  ui taking more time to open.
2. when use this event [emojisToShowFilter]="filter" then search filter not working

Version :
"@ctrl/ngx-emoji-mart": "^1.0.6",
"@angular/cli": "~8.1.2",

this one i am using :
 <emoji-mart [showPreview]="false" [isNative]="true" [set]="native" (emojiClick)="addEmoji($event)"
    [showSingleCategory]="false" [emojisToShowFilter]="filter" [enableSearch]="false"
 [style]="{ position: 'absolute', bottom: '60px', right: '0px' }"></emoji-mart>

filter(fullCode: string) {
    if (fullCode && typeof fullCode === 'string') {
      const code = fullCode.split('-')[0]

      if (!isNaN(Number(`0x${code}`))) { 
        const emoji = String.fromCodePoint(Number(`0x${code}`));
        return ifEmoji(emoji);
      } else {
        return false;
      }
    } else {
      return false;
    }
  }

Thanks in advance.

**Comment by scttcper** [comment]
there was some fixes around the filter in the latest version

**Comment by chirantan369** [comment]
@scttcper thanks for your quick response. but the latest version not working in angular 8.1.2 while build getting "kind" error.

**Comment by scttcper** [comment]
Latest requires angular 9

**Comment by chirantan369** [comment]
Ok thanks, any other way to handle that error in angular 8.1.2
