### ISSUE TITLE
How to use it with textarea or input field

### ISSUE THREAD

**Issue by zamananjum0** [TypeCtrl/ngx-emoji-mart#36]
I'm using angular 5 and i want to use it in my app,kindly tell me the details how to use inline emojis with text area and how it bind with model

**Comment by btxtiger** [comment]
I guess the only way ist to use `<div contenteditable="true"></div>`

**Comment by raDiesle** [comment]
Serious? In my use case, Emoji is used for chat...

**Comment by DanielKucal** [comment]
@raDiesle, I guess you have to wait for https://github.com/TypeCtrl/ngx-emoji-mart/issues/89

**Comment by vivekdoshi2** [comment]
@DanielKucal , Any update on this ?

**Comment by scttcper** [comment]
closed in favor of #89
