### ISSUE TITLE
fetching this issu in angular 16.1.6

### ISSUE THREAD

**Issue by kevinkmulani** [TypeCtrl/ngx-emoji-mart#433]
![image](https://github.com/scttcper/ngx-emoji-mart/assets/79919227/13798094-d988-4852-afd0-ffffbf948c26)

**Comment by ca-vladyslavhaidar** [comment]
is there any updated about this issue?

**Comment by sourvil** [comment]
Same problem here. Typescript restriction makes also problem.

**Comment by jeanpaulattard** [comment]
Ran into the same problem... Anyone managed to find a solution for this?

**Comment by dariusbzo** [comment]
I had to update `rxjs` version in order make it work.
