### ISSUE TITLE
Showing the wrong emojis

### ISSUE THREAD

**Issue by apangr** [TypeCtrl/ngx-emoji-mart#435]
Using "**@angular/core": "^15.0.0**" and  "**@ctrl/ngx-emoji-mart": "^8.2.0**".

**app.module.ts**
`import { PickerModule } from '@ctrl/ngx-emoji-mart';
...
imports: [
...
PickerModule]`

**component.component.html**
`<emoji-mart
              class="emoji-mart"
              (emojiSelect)="addEmoji($event)"
              title="Pick your emoji…"
            ></emoji-mart>`

The library is showing the wrong emojis:

![image 1](https://github.com/scttcper/ngx-emoji-mart/assets/48444415/3fe29a4e-0d57-4cf9-b7f6-356478e52cf3)

**Comment by scttcper** [comment]
I'd try 9.2.0 or manually adjust the sheetsizes and sheets being used.
