### ISSUE TITLE
Angular version 9 is not compatible with 3.1 now 

### ISSUE THREAD

**Issue by Shyamkr1** [TypeCtrl/ngx-emoji-mart#436]
i am getting error
'PickerComponent' does not appear to be an NgModule class.(-996002)
picker.component.d.ts(5, 49): This likely means that the library (@ctrl/ngx-emoji-mart) which declares PickerComponent is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
(alias) class PickerComponent
import PickerComponent.
even i tried all version

**Comment by scttcper** [comment]
version 9?

**Comment by scttcper** [comment]
reinstall and make sure you're using the right version of angular

**Comment by Shyamkr1** [comment]
ERROR in
***@***.***/ngx-emoji-mart/ngx-emoji/emoji.component.d.ts:77:21 -
error TS2694: Namespace
***@***.***/core/core"' has no
exported member 'ɵɵFactoryDeclaration'.

77     static ɵfac: i0.ɵɵFactoryDeclaration<EmojiComponent, never>;

**Comment by Shyamkr1** [comment]
ERROR in
.***@***.***/ngx-emoji-mart/fesm2022/ctrl-ngx-emoji-mart.mjs 12:15
Module parse failed: Unexpected token (12:15)
You may need an appropriate loader to handle this file type, currently no
loaders are configured to process this file. See
https://webpack.js.org/concepts#loaders
|
| class AnchorsComponent {
>     categories = [];
|     color;
|     selected;

**Comment by Shyamkr1** [comment]
***@***.***/flex-layout/grid/typings/areas/areas.d.ts:19:18 -
error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

19     static ɵfac: ɵngcc0.ɵɵFactoryDef<GridAreasStyleBuiler>;
