### ISSUE TITLE
Some emojis do not display properly

### ISSUE THREAD

**Issue by fengzhihenxs** [TypeCtrl/ngx-emoji-mart#442]
Hello, when I use ngx-emoji-mart, some emoticons cannot be displayed properly on some computers, including the official demo (https://ngx-emoji-mart.vercel.app/). Why? How to solve it?

Thank you.

![image](https://github.com/scttcper/ngx-emoji-mart/assets/37610470/9e5bfdd4-1ad6-4610-a176-aa056b24fd9d)

**Comment by scttcper** [comment]
update your operating system or use an emoji pack

**Comment by fengzhihenxs** [comment]
Thank you for your reply. How do I use emoji packs?-------- 原始邮件 --------发件人： Scott Cooper ***@***.***>日期： 2024年4月9日周二 22:29收件人： scttcper/ngx-emoji-mart ***@***.***>抄送： fengzhihenxs ***@***.***>, Author ***@***.***>主    题： Re: [scttcper/ngx-emoji-mart] Some emojis do not display properly (Issue #442)
update your operating system or use an emoji pack
