### ISSUE TITLE
Blocking UI when open in modal

### ISSUE THREAD

**Issue by googlicius** [TypeCtrl/ngx-emoji-mart#51]
Hello,
Thank you for creating this with Angular.
I just added ngx-emoji-mart to my project and I got an issue when I put `<emoji-mart set="twitter" title="Pick your emoji…" emoji="point_up"></emoji-mart>` to modal body and It block the UI about 1 second when I open the modal.

It also block UI when I navigate to a screen that use emoji-mart.
I reproduce issue with navigating:
https://stackblitz.com/edit/angular-egigxh
https://angular-egigxh.stackblitz.io/

My package.json:
```
"@angular/animations": "^5.2.9",
"@angular/common": "^5.2.9",
"@angular/compiler": "^5.2.9",
"@angular/core": "^5.2.9",
"@angular/forms": "^5.2.9",
"@angular/http": "^5.2.9",
"@angular/platform-browser": "^5.2.9",
"@angular/platform-browser-dynamic": "^5.2.9",
"@angular/platform-server": "^5.2.9",
"@angular/router": "^5.2.9",
"@ctrl/ngx-emoji-mart": "^0.2.1",
"@ng-bootstrap/ng-bootstrap": "^1.1.1",
"core-js": "^2.5.4",
"ng2-device-detector": "^1.0.1",
"rxjs": "^5.5.8",
"typed.js": "^2.0.6",
"zone.js": "^0.8.25"
```

**Comment by scttcper** [comment]
I've added the approach that the original emoji mart uses. With custom emoji it might still take a while, but with native emoji it went from ~1sec to ~200ms

**Comment by scttcper** [comment]
Here's a fork of your stackblitz with v0.3.0. https://angular-gdr6n2.stackblitz.io/emojis thanks for making that btw
