### ISSUE TITLE
Unexpected value 'PickerModule' when i 'ng build --prod'

### ISSUE THREAD

**Issue by nviethuan** [TypeCtrl/ngx-emoji-mart#57]
ERROR in : Unexpected value 'PickerModule in E:/Programings/angular/ng-emoji-picker-demo/node_modules/@ctrl/ngx-emoji-mart/picker.module.d.ts' imported by the module 'AppModule in E:/Programings/angular/ng-emoji-picker-demo/src/app/app.module.ts'. Please add a @NgModule annotation.

**Comment by scttcper** [comment]
what version of typescript?
