### ISSUE TITLE
Metadata version mismatch for module - found version 4, expected 3

### ISSUE THREAD

**Issue by shashiakosha** [TypeCtrl/ngx-emoji-mart#61]
Metadata version mismatch for module - found version 4, expected 3

**Comment by shashiakosha** [comment]
node_modules/@ctrl/ngx-emoji-mart/ctrl-ngx-emoji-mart.d.ts, found version 4, expected 3,

**Comment by scttcper** [comment]
requires angular > 5

**Comment by shashiakosha** [comment]
if i have to use with angular 4 then which version is compatible

**Comment by scttcper** [comment]
none

**Comment by shashiakosha** [comment]
what needs to be change to  add support for angular 4

**Comment by shashiakosha** [comment]
?

**Comment by shashiakosha** [comment]
@scttcper can you please help here, what needs to be change to have a support with angular 4
